### PR TITLE
Allow adding custom cli args

### PR DESCRIPTION
**Pull request by evanlinjin**
Also added `Args::cp_limit`.

### CODE REVIEW

**Review by rajarshimaitra — APPROVED** [review]
ACK 8e9395902d21576a531516a0ef28b61a7d7470ff

**Comment by LLFourn** [comment]
ACK though in practice I think we should not put rpc args at the top level. The rpc args should be put on the actual command that uses them. Otherwise, It strongly implies to someone that every command needs these arguments.

**Comment by evanlinjin** [comment]
> ACK though in practice I think we should not put rpc args at the top level. The rpc args should be put on the actual command that uses them. Otherwise, It strongly implies to someone that every command needs these arguments.

What do you mean by RPC Args?

**Comment by LLFourn** [comment]
@evanlinjin I mean that it should be an argument to the subcommand only.

**Comment by evanlinjin** [comment]
As discussed with @LLFourn, I am convinced that `chain_args` is not needed. However, `cp_limit` will still be helpful.

**Pull request closed without merging**
