### PR TITLE
Add KeychainTxOutIndex::reserve_next_unused_spk #188

### LINKED ISSUE #188: Add KeychainTxOutIndex::reserve_next_unused_spk
Just like `next_unused_spk` but also marks it as used with `mark_used`. It's annoying to do this in two steps outside because of mutable borrow issues.

Should also have one for revealing and reserving at the same time.

Alternatively we could have returned owned `Script`s from all spk APIs. I liked returning references because it demonstrates what is actually stored in the index and what is being derived on the fly.

### PR DESCRIPTION
**Pull request by LagginTimes**
Fixes #188 
Second method will be done later this week.

### CODE REVIEW

**Comment by LLFourn** [comment]
LGTM! I think I still like this approach over the alternative which is to return an owned `Script` from `next_unused_spk`.

**Comment by evanlinjin** [comment]
> LGTM! I think I still like this approach over the alternative which is to return an owned `Script` from `next_unused_spk`. 

Should we change `next_unused_spk` to return a referenced spk as well?

**Comment by evanlinjin** [comment]
LGTM as well. I was talking to @LLFourn about this PR today and he suggested to add tests for these added methods. Let me know if you need some direction for this :)

**Review by evanlinjin — APPROVED** [review]
ACK d183b9dc8a113987bda36b9a294748aeb7799a4d

LGTM!

**Pull request merged**
