### PR TITLE
Update varint_size to use rust-bitcoin values

### PR DESCRIPTION
**Pull request by danielabrozzoni**
Sorry for the nit 🥺

### CODE REVIEW

**Review by evanlinjin — COMMENTED** [review]
utACK

Brownie points for the test. However @LLFourn is doing some massive refactoring with the coin select module, which may cause conflicts.

**Comment by danielabrozzoni** [comment]
No problem for me, it can stay open for months. The current code is good anyways

**Review by LLFourn — APPROVED** [review]
Thanks! I think I might remove the tests before merging since if there's tests for this they should be in rust-bitcoin.

**Comment by danielabrozzoni** [comment]
> Thanks! I think I might remove the tests before merging since if there's tests for this they should be in rust-bitcoin.

Sure, I put them there just to double check that it behaved exactly like the old implementation

**Comment by danielabrozzoni** [comment]
Removed :)

**Pull request merged**
